# Generated by Django 5.1.5 on 2025-02-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
